version: "3"
services:
  web:
    container_name: ensave
    image: ensave_image:latest
    volumes:
      - /Users/becky/Documents/log/:/log
    ports:
      - 8000:8000
    restart: always
    command: uwsgi --ini /ENSAVE/uwsgi.ini
